import { StyleSheet } from "react-native";

export const getStyles = (theme) =>
  StyleSheet.create({
    containerButtons: {
      padding: 16,
      justifyContent: "center",
    },
    container: {
      flex: 1,
      backgroundColor: "rgba(189, 189, 189, 0.43)",
      justifyContent: "center",
    },
    innerContainer: {
      alignItems: "center",
      justifyContent: "center",
    },

    backgroundImage: {
      flex: 1,
      width: "100%",
      height: "100%",
      resizeMode: "cover",
    },
    containerScrollView: {
      padding: 16,
      flex: 1,
      backgroundColor: "rgba(189, 189, 189, 0.43)",
    },
    containerContent: {
      padding: 16,
      flex: 1,
      backgroundColor: "rgba(189, 189, 189, 0.43)",
      justifyContent: "center",
    },
    mapContainer: {
      flex: 1,
      padding: 5,
      backgroundColor: "rgba(189, 189, 189, 0.43)",
    },
    title: {
      fontSize: 28,
      fontFamily: "Exo2-Bold",
      color: theme.colors.text,
      marginBottom: 20,
      textShadowColor: "rgba(87, 87, 87, 0.7)",
      textShadowOffset: { width: 2, height: 2 },
      textShadowRadius: 3,
    },
    subtitle: {
      fontSize: 20,
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      textShadowColor: theme.colors.button,
      textShadowOffset: { width: 2, height: 2 },
      textShadowRadius: 3,
    },
    subtitle2: {
      fontSize: 18,
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      marginBottom: 20,
      textShadowColor: "rgba(61, 61, 61, 0.7)",
      textShadowOffset: { width: 3, height: 3 },
      textShadowRadius: 3,
    },
    card: {
      flexDirection: "row",
      alignItems: "center",
      padding: 16,
      borderRadius: 8,
      backgroundColor: theme.colors.card,
      marginBottom: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    searchBox: {
      fontSize: 16,
      fontFamily: "Exo2-Regular",
      padding: 10,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 8,
      marginBottom: 16,
      color: theme.colors.text,
      backgroundColor: theme.colors.card,
    },
    flag: {
      width: 100,
      height: 60,
      marginRight: 16,
      borderRadius: 4,
    },
    flagCountryDetails: {
      width: "100%",
      height: 150,
      marginBottom: 16,
      borderRadius: 8,
    },
    detailsCountryDetails: {
      padding: 16,
      width: "100%",
      backgroundColor: theme.colors.card,
      borderRadius: 8,
      marginBottom: 16,
    },
    buttonContainerCountryDetails: {
      marginTop: 16,
      alignItems: "center",
      backgroundColor: "#6200ee",
      padding: 12,
      borderRadius: 8,
    },
    cardContent: {
      flex: 1,
    },
    countryName: {
      fontSize: 18,
      fontFamily: "Exo2-Bold",
      color: theme.colors.text,
    },
    capitalText: {
      fontSize: 14,
      color: "#666666",
      fontFamily: "Exo2-Bold",
    },
    button: {
      backgroundColor: theme.colors.button,
      padding: 20,
      borderRadius: 8,
      alignItems: "center",
      marginBottom: 12,
    },
    buttonText: {
      color: theme.colors.buttonText,
      fontFamily: "Exo2-Bold",
      fontSize: 15,
    },
    settingItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
      padding: 12,
      backgroundColor: theme.colors.card,
      borderRadius: 8,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    picker: {
      width: 150,
      backgroundColor: theme.colors.card,
      borderRadius: 8,
      color: theme.colors.buttonText,
    },
    loaderContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      marginTop: 20,
    },
  });
