import { StyleSheet } from "react-native";

export const getStyles = (theme) =>
  StyleSheet.create({
    containerButtons: {
      padding: 16,
      justifyContent: "center",
    },
    container: {
      flex: 1,
      backgroundColor: "rgba(189, 189, 189, 0.43)",
      justifyContent: "center",
    },
    homeScroll: {
      flex: 1,
      backgroundColor: theme.isDarkMode
        ? "rgba(11, 11, 22, 0.78)"
        : "rgba(248, 250, 252, 0.82)",
    },
    homeScrollContent: {
      padding: 16,
      paddingTop: 28,
      paddingBottom: 32,
    },
    homeHero: {
      alignItems: "center",
      marginBottom: 16,
    },
    homeGlobe: {
      width: 140,
      height: 140,
      alignSelf: "center",
    },
    homeEyebrow: {
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      fontSize: 11,
      letterSpacing: 0,
      textTransform: "uppercase",
      opacity: 0.7,
      marginTop: 2,
    },
    homeTitle: {
      fontSize: 28,
      lineHeight: 34,
      fontFamily: "Exo2-Bold",
      color: theme.colors.text,
      textAlign: "center",
      marginTop: 8,
    },
    homeSubtitle: {
      fontSize: 14,
      lineHeight: 20,
      fontFamily: "Exo2-Regular",
      color: theme.colors.text,
      opacity: 0.78,
      textAlign: "center",
      marginTop: 8,
      maxWidth: 320,
    },
    homeQuickActions: {
      width: "100%",
      marginBottom: 12,
    },
    homeActionGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      rowGap: 10,
    },
    homeActionCard: {
      width: "48.5%",
      minHeight: 126,
      padding: 14,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.card,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.13,
      shadowRadius: 6,
      elevation: 3,
    },
    homeActionIcon: {
      width: 40,
      height: 40,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.button,
      marginBottom: 12,
    },
    homeActionTitle: {
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      fontSize: 16,
      lineHeight: 21,
    },
    homeActionSubtitle: {
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      fontSize: 12,
      lineHeight: 17,
      opacity: 0.72,
      marginTop: 4,
    },
    innerContainer: {
      alignItems: "center",
      justifyContent: "center",
    },

    backgroundImage: {
      flex: 1,
      width: "100%",
      height: "100%",
      resizeMode: "cover",
    },
    containerScrollView: {
      padding: 16,
      flex: 1,
      backgroundColor: "rgba(189, 189, 189, 0.43)",
    },
    containerContent: {
      padding: 16,
      flex: 1,
      backgroundColor: "rgba(189, 189, 189, 0.43)",
      justifyContent: "flex-start",
    },
    mapContainer: {
      flex: 1,
      padding: 5,
      backgroundColor: "rgba(189, 189, 189, 0.43)",
    },
    title: {
      fontSize: 28,
      fontFamily: "Exo2-Bold",
      color: theme.colors.text,
      marginBottom: 20,
      textShadowColor: "rgba(87, 87, 87, 0.7)",
      textShadowOffset: { width: 2, height: 2 },
      textShadowRadius: 3,
    },
    subtitle: {
      fontSize: 20,
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      textShadowColor: theme.colors.button,
      textShadowOffset: { width: 2, height: 2 },
      textShadowRadius: 3,
    },
    subtitle2: {
      fontSize: 18,
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      marginBottom: 20,
      textShadowColor: "rgba(61, 61, 61, 0.7)",
      textShadowOffset: { width: 3, height: 3 },
      textShadowRadius: 3,
    },
    card: {
      flexDirection: "row",
      alignItems: "center",
      padding: 12,
      borderRadius: 8,
      backgroundColor: theme.colors.card,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    searchBox: {
      fontSize: 16,
      fontFamily: "Exo2-Regular",
      paddingVertical: 10,
      paddingHorizontal: 8,
      flex: 1,
      color: theme.colors.text,
      backgroundColor: "transparent",
    },
    searchInputWrap: {
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 8,
      paddingHorizontal: 12,
      marginTop: 14,
      backgroundColor: theme.isDarkMode
        ? "rgba(255, 255, 255, 0.06)"
        : "rgba(255, 255, 255, 0.82)",
    },
    flag: {
      width: 62,
      height: 40,
      marginRight: 12,
      borderRadius: 4,
    },
    flagCountryDetails: {
      width: "100%",
      height: 150,
      marginBottom: 16,
      borderRadius: 8,
    },
    detailsCountryDetails: {
      padding: 16,
      width: "100%",
      backgroundColor: theme.colors.card,
      borderRadius: 8,
      marginBottom: 16,
    },
    buttonContainerCountryDetails: {
      marginTop: 16,
      alignItems: "center",
      backgroundColor: "#6200ee",
      padding: 12,
      borderRadius: 8,
    },
    cardContent: {
      flex: 1,
    },
    dailyCountryCard: {
      width: "100%",
      padding: 14,
      borderRadius: 8,
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    dailyCountryHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 8,
    },
    dailyCountryEyebrow: {
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      fontSize: 13,
      opacity: 0.8,
    },
    dailyCountryContent: {
      flexDirection: "row",
      alignItems: "center",
    },
    dailyCountryFlag: {
      width: 72,
      height: 46,
      borderRadius: 4,
      marginRight: 12,
    },
    dailyCountryText: {
      flex: 1,
    },
    dailyCountryAction: {
      color: theme.colors.button,
      fontFamily: "Exo2-Bold",
      fontSize: 13,
    },
    dailyCountryActionRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      marginTop: 8,
    },
    dailyCountryLoader: {
      alignSelf: "flex-start",
      marginVertical: 8,
    },
    countryName: {
      fontSize: 18,
      fontFamily: "Exo2-Bold",
      color: theme.colors.text,
    },
    capitalText: {
      fontSize: 14,
      color: "#666666",
      fontFamily: "Exo2-Bold",
    },
    countryMetaText: {
      fontSize: 13,
      lineHeight: 18,
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      opacity: 0.72,
      marginTop: 3,
    },
    button: {
      backgroundColor: theme.colors.button,
      padding: 20,
      borderRadius: 8,
      alignItems: "center",
      marginBottom: 12,
    },
    correctOption: {
      backgroundColor: "#1B7F4C",
    },
    incorrectOption: {
      backgroundColor: "#B42318",
    },
    quizFeedbackCard: {
      padding: 16,
      borderRadius: 8,
      backgroundColor: theme.colors.card,
      marginBottom: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    quizFeedbackTitle: {
      fontSize: 20,
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      marginBottom: 8,
    },
    quizFeedbackText: {
      fontSize: 16,
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      marginBottom: 8,
    },
    buttonText: {
      color: theme.colors.buttonText,
      fontFamily: "Exo2-Bold",
      fontSize: 15,
    },
    settingItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
      padding: 12,
      backgroundColor: theme.colors.card,
      borderRadius: 8,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    settingItemColumn: {
      marginBottom: 16,
      padding: 12,
      backgroundColor: theme.colors.card,
      borderRadius: 8,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    settingDescription: {
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      fontSize: 14,
      marginTop: 8,
    },
    settingMetaText: {
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      fontSize: 13,
      marginTop: 10,
      opacity: 0.8,
    },
    settingError: {
      color: "#B42318",
      fontFamily: "Exo2-Bold",
      fontSize: 13,
      marginTop: 8,
    },
    settingLoader: {
      alignSelf: "flex-start",
      marginTop: 12,
    },
    settingActions: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginTop: 12,
    },
    settingActionButton: {
      backgroundColor: theme.colors.button,
      borderRadius: 8,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    settingActionButtonSecondary: {
      backgroundColor: "#3B82F6",
      borderRadius: 8,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    settingActionButtonDisabled: {
      opacity: 0.5,
    },
    settingActionText: {
      color: theme.colors.buttonText,
      fontFamily: "Exo2-Bold",
      fontSize: 14,
    },
    settingLinkText: {
      color: "#3B82F6",
      textDecorationLine: "underline",
    },
    picker: {
      width: 150,
      backgroundColor: theme.colors.card,
      borderRadius: 8,
      color: theme.colors.buttonText,
    },
    loaderContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      marginTop: 20,
    },
    exploreHeaderCard: {
      padding: 14,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.card,
      marginTop: 20,
      marginBottom: 14,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    exploreListContent: {
      paddingBottom: 96,
    },
    exploreEmptyState: {
      alignItems: "center",
      justifyContent: "center",
      padding: 24,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.card,
    },
  });
