import { StyleSheet } from "react-native";

export const getStyles = (theme) =>
  StyleSheet.create({
    containerButtons: {
      padding: 16,
      justifyContent: "center",
    },
    container: {
      flex: 1,
      backgroundColor: "rgba(189, 189, 189, 0.43)",
      justifyContent: "center",
    },
    innerContainer: {
      alignItems: "center",
      justifyContent: "center",
    },

    backgroundImage: {
      flex: 1,
      width: "100%",
      height: "100%",
      resizeMode: "cover",
    },
    containerScrollView: {
      padding: 16,
      flex: 1,
      backgroundColor: "rgba(189, 189, 189, 0.43)",
    },
    containerContent: {
      padding: 16,
      flex: 1,
      backgroundColor: "rgba(189, 189, 189, 0.43)",
      justifyContent: "center",
    },
    mapContainer: {
      flex: 1,
      padding: 5,
      backgroundColor: "rgba(189, 189, 189, 0.43)",
    },
    title: {
      fontSize: 28,
      fontFamily: "Exo2-Bold",
      color: theme.colors.text,
      marginBottom: 20,
      textShadowColor: "rgba(87, 87, 87, 0.7)",
      textShadowOffset: { width: 2, height: 2 },
      textShadowRadius: 3,
    },
    subtitle: {
      fontSize: 20,
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      textShadowColor: theme.colors.button,
      textShadowOffset: { width: 2, height: 2 },
      textShadowRadius: 3,
    },
    subtitle2: {
      fontSize: 18,
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      marginBottom: 20,
      textShadowColor: "rgba(61, 61, 61, 0.7)",
      textShadowOffset: { width: 3, height: 3 },
      textShadowRadius: 3,
    },
    card: {
      flexDirection: "row",
      alignItems: "center",
      padding: 16,
      borderRadius: 8,
      backgroundColor: theme.colors.card,
      marginBottom: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    searchBox: {
      fontSize: 16,
      fontFamily: "Exo2-Regular",
      padding: 10,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 8,
      marginBottom: 16,
      color: theme.colors.text,
      backgroundColor: theme.colors.card,
    },
    flag: {
      width: 100,
      height: 60,
      marginRight: 16,
      borderRadius: 4,
    },
    flagCountryDetails: {
      width: "100%",
      height: 150,
      marginBottom: 16,
      borderRadius: 8,
    },
    countryDetailsContent: {
      paddingBottom: 24,
    },
    countryBackRow: {
      alignSelf: "flex-start",
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingVertical: 8,
      paddingRight: 12,
      marginBottom: 8,
    },
    countryBackText: {
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      fontSize: 15,
    },
    countryHeroCard: {
      width: "100%",
      height: 170,
      borderRadius: 8,
      overflow: "hidden",
      backgroundColor: theme.colors.card,
      marginBottom: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.14,
      shadowRadius: 7,
      elevation: 4,
    },
    countryHeroFlag: {
      width: "100%",
      height: "100%",
    },
    countryHeroOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "rgba(0, 0, 0, 0.28)",
    },
    countryHeroText: {
      position: "absolute",
      left: 16,
      right: 16,
      bottom: 14,
    },
    countryHeroName: {
      color: "#FFFFFF",
      fontFamily: "Exo2-Bold",
      fontSize: 28,
      textShadowColor: "rgba(0, 0, 0, 0.45)",
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 4,
    },
    countryHeroRegion: {
      color: "#FFFFFF",
      fontFamily: "Exo2-Regular",
      fontSize: 15,
      marginTop: 4,
      opacity: 0.92,
    },
    countryTabRow: {
      flexDirection: "row",
      gap: 8,
      marginBottom: 14,
    },
    countryTab: {
      flex: 1,
      minHeight: 42,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    countryTabActive: {
      backgroundColor: theme.colors.button,
      borderColor: theme.colors.button,
    },
    countryTabText: {
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      fontSize: 13,
    },
    countryTabTextActive: {
      color: theme.colors.buttonText,
    },
    countryStatGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      marginBottom: 14,
    },
    countryStatCard: {
      width: "48%",
      minHeight: 88,
      padding: 12,
      borderRadius: 8,
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
      justifyContent: "space-between",
    },
    countryStatLabel: {
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      fontSize: 12,
      opacity: 0.72,
      textTransform: "uppercase",
    },
    countryStatValue: {
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      fontSize: 16,
      marginTop: 8,
    },
    countryFactCard: {
      padding: 14,
      borderRadius: 8,
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: 14,
    },
    countryFactHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginBottom: 8,
    },
    countryFactLabel: {
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      fontSize: 12,
      textTransform: "uppercase",
    },
    countryFactText: {
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      fontSize: 14,
      lineHeight: 20,
    },
    countryMiniMapCard: {
      height: 230,
      borderRadius: 8,
      overflow: "hidden",
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: 14,
    },
    countryMiniMap: {
      flex: 1,
    },
    countryCtaContent: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    detailsCountryDetails: {
      padding: 16,
      width: "100%",
      backgroundColor: theme.colors.card,
      borderRadius: 8,
      marginBottom: 16,
    },
    buttonContainerCountryDetails: {
      marginTop: 16,
      alignItems: "center",
      backgroundColor: "#6200ee",
      padding: 12,
      borderRadius: 8,
    },
    cardContent: {
      flex: 1,
    },
    dailyCountryCard: {
      width: "100%",
      padding: 12,
      borderRadius: 8,
      backgroundColor: theme.colors.card,
      marginBottom: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    dailyCountryEyebrow: {
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      fontSize: 13,
      marginBottom: 8,
      opacity: 0.8,
    },
    dailyCountryContent: {
      flexDirection: "row",
      alignItems: "center",
    },
    dailyCountryFlag: {
      width: 72,
      height: 46,
      borderRadius: 4,
      marginRight: 12,
    },
    dailyCountryText: {
      flex: 1,
    },
    dailyCountryAction: {
      color: "#3B82F6",
      fontFamily: "Exo2-Bold",
      fontSize: 13,
      marginTop: 8,
      textDecorationLine: "underline",
    },
    dailyCountryLoader: {
      alignSelf: "flex-start",
      marginVertical: 8,
    },
    countryName: {
      fontSize: 18,
      fontFamily: "Exo2-Bold",
      color: theme.colors.text,
    },
    capitalText: {
      fontSize: 14,
      color: "#666666",
      fontFamily: "Exo2-Bold",
    },
    button: {
      backgroundColor: theme.colors.button,
      padding: 20,
      borderRadius: 8,
      alignItems: "center",
      marginBottom: 12,
    },
    correctOption: {
      backgroundColor: "#1B7F4C",
    },
    incorrectOption: {
      backgroundColor: "#B42318",
    },
    quizFeedbackCard: {
      padding: 16,
      borderRadius: 8,
      backgroundColor: theme.colors.card,
      marginBottom: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    quizFeedbackTitle: {
      fontSize: 20,
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      marginBottom: 8,
    },
    quizFeedbackText: {
      fontSize: 16,
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      marginBottom: 8,
    },
    buttonText: {
      color: theme.colors.buttonText,
      fontFamily: "Exo2-Bold",
      fontSize: 15,
    },
    settingItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
      padding: 12,
      backgroundColor: theme.colors.card,
      borderRadius: 8,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    settingItemColumn: {
      marginBottom: 16,
      padding: 12,
      backgroundColor: theme.colors.card,
      borderRadius: 8,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    settingDescription: {
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      fontSize: 14,
      marginTop: 8,
    },
    settingMetaText: {
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      fontSize: 13,
      marginTop: 10,
      opacity: 0.8,
    },
    settingError: {
      color: "#B42318",
      fontFamily: "Exo2-Bold",
      fontSize: 13,
      marginTop: 8,
    },
    settingLoader: {
      alignSelf: "flex-start",
      marginTop: 12,
    },
    settingActions: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginTop: 12,
    },
    settingActionButton: {
      backgroundColor: theme.colors.button,
      borderRadius: 8,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    settingActionButtonSecondary: {
      backgroundColor: "#3B82F6",
      borderRadius: 8,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    settingActionButtonDisabled: {
      opacity: 0.5,
    },
    settingActionText: {
      color: theme.colors.buttonText,
      fontFamily: "Exo2-Bold",
      fontSize: 14,
    },
    settingLinkText: {
      color: "#3B82F6",
      textDecorationLine: "underline",
    },
    picker: {
      width: 150,
      backgroundColor: theme.colors.card,
      borderRadius: 8,
      color: theme.colors.buttonText,
    },
    loaderContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      marginTop: 20,
    },
  });
