import { StyleSheet } from "react-native";

interface Theme {
  isDarkMode: boolean;
  colors: {
    text: string;
    button: string;
    buttonText: string;
    card: string;
    border: string;
  };
}

export const getStyles = (theme: Theme) =>
  StyleSheet.create({
    containerButtons: {
      padding: 16,
      justifyContent: "center",
    },
    container: {
      flex: 1,
      backgroundColor: "rgba(189, 189, 189, 0.43)",
      justifyContent: "center",
    },
    homeScroll: {
      flex: 1,
      backgroundColor: theme.isDarkMode
        ? "rgba(11, 11, 22, 0.78)"
        : "rgba(248, 250, 252, 0.82)",
    },
    homeScrollContent: {
      padding: 16,
      paddingTop: 28,
      paddingBottom: 32,
    },
    homeHero: {
      alignItems: "center",
      marginBottom: 16,
    },
    homeGlobe: {
      width: 140,
      height: 140,
      alignSelf: "center",
    },
    homeEyebrow: {
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      fontSize: 11,
      letterSpacing: 0,
      textTransform: "uppercase",
      opacity: 0.7,
      marginTop: 2,
    },
    homeTitle: {
      fontSize: 28,
      lineHeight: 34,
      fontFamily: "Exo2-Bold",
      color: theme.colors.text,
      textAlign: "center",
      marginTop: 8,
    },
    homeSubtitle: {
      fontSize: 14,
      lineHeight: 20,
      fontFamily: "Exo2-Regular",
      color: theme.colors.text,
      opacity: 0.78,
      textAlign: "center",
      marginTop: 8,
      maxWidth: 320,
    },
    homeQuickActions: {
      width: "100%",
      marginBottom: 12,
    },
    homeActionGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      rowGap: 10,
    },
    homeActionCard: {
      width: "48.5%",
      minHeight: 126,
      padding: 14,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.card,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.13,
      shadowRadius: 6,
      elevation: 3,
    },
    homeActionIcon: {
      width: 40,
      height: 40,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.button,
      marginBottom: 12,
    },
    homeActionTitle: {
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      fontSize: 16,
      lineHeight: 21,
    },
    homeActionSubtitle: {
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      fontSize: 12,
      lineHeight: 17,
      opacity: 0.72,
      marginTop: 4,
    },
    innerContainer: {
      alignItems: "center",
      justifyContent: "center",
    },

    backgroundImage: {
      flex: 1,
      width: "100%",
      height: "100%",
      resizeMode: "cover",
    },
    containerScrollView: {
      padding: 16,
      flex: 1,
      backgroundColor: "rgba(189, 189, 189, 0.43)",
    },
    containerContent: {
      padding: 16,
      flex: 1,
      backgroundColor: "rgba(189, 189, 189, 0.43)",
      justifyContent: "flex-start",
    },
    mapContainer: {
      flex: 1,
      padding: 5,
      backgroundColor: "rgba(189, 189, 189, 0.43)",
    },
    mapContent: {
      flex: 1,
      padding: 16,
      paddingTop: 18,
      backgroundColor: theme.isDarkMode
        ? "rgba(11, 11, 22, 0.78)"
        : "rgba(248, 250, 252, 0.82)",
    },
    mapHeaderRow: {
      alignSelf: "flex-start",
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingVertical: 8,
      paddingRight: 12,
      marginBottom: 4,
    },
    mapShell: {
      flex: 1,
      minHeight: 360,
      borderRadius: 8,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.card,
      position: "relative",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.14,
      shadowRadius: 7,
      elevation: 4,
    },
    mapView: {
      flex: 1,
    },
    mapControls: {
      position: "absolute",
      right: 10,
      top: 10,
      gap: 8,
    },
    mapControlButton: {
      width: 38,
      height: 38,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.card,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.13,
      shadowRadius: 4,
      elevation: 3,
    },
    mapPin: {
      alignItems: "center",
      justifyContent: "center",
    },
    mapTooltip: {
      minWidth: 164,
      maxWidth: 220,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      padding: 10,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.card,
    },
    mapTooltipFlag: {
      width: 34,
      height: 22,
      borderRadius: 4,
      backgroundColor: "rgba(120, 120, 120, 0.18)",
    },
    mapTooltipText: {
      flex: 1,
    },
    mapTooltipName: {
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      fontSize: 13,
    },
    mapTooltipMeta: {
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      fontSize: 11,
      marginTop: 2,
      opacity: 0.74,
    },
    mapLegend: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center",
      gap: 12,
      paddingVertical: 14,
    },
    mapLegendItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    mapLegendDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
    },
    mapLegendDotOutline: {
      backgroundColor: "transparent",
      borderWidth: 1,
      borderColor: theme.colors.text,
    },
    mapLegendText: {
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      fontSize: 12,
      opacity: 0.78,
    },
    title: {
      fontSize: 28,
      fontFamily: "Exo2-Bold",
      color: theme.colors.text,
      marginBottom: 20,
      textShadowColor: "rgba(87, 87, 87, 0.7)",
      textShadowOffset: { width: 2, height: 2 },
      textShadowRadius: 3,
    },
    subtitle: {
      fontSize: 20,
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      textShadowColor: theme.colors.button,
      textShadowOffset: { width: 2, height: 2 },
      textShadowRadius: 3,
    },
    subtitle2: {
      fontSize: 18,
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      marginBottom: 20,
      textShadowColor: "rgba(61, 61, 61, 0.7)",
      textShadowOffset: { width: 3, height: 3 },
      textShadowRadius: 3,
    },
    card: {
      flexDirection: "row",
      alignItems: "center",
      padding: 12,
      borderRadius: 8,
      backgroundColor: theme.colors.card,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    searchBox: {
      fontSize: 16,
      fontFamily: "Exo2-Regular",
      paddingVertical: 10,
      paddingHorizontal: 8,
      flex: 1,
      color: theme.colors.text,
      backgroundColor: "transparent",
    },
    searchInputWrap: {
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 8,
      paddingHorizontal: 12,
      marginTop: 14,
      backgroundColor: theme.isDarkMode
        ? "rgba(255, 255, 255, 0.06)"
        : "rgba(255, 255, 255, 0.82)",
    },
    exploreHeaderRow: {
      marginBottom: 4,
    },
    exploreSearchContainer: {
      minHeight: 48,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 8,
      marginBottom: 12,
      backgroundColor: theme.colors.card,
    },
    exploreSearchInput: {
      flex: 1,
      minHeight: 48,
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      fontSize: 15,
      paddingVertical: 0,
    },
    regionFilterRow: {
      flexGrow: 0,
      marginBottom: 14,
    },
    regionFilterContent: {
      gap: 8,
      paddingRight: 8,
    },
    regionFilterChip: {
      minHeight: 38,
      paddingHorizontal: 14,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.card,
      alignItems: "center",
      justifyContent: "center",
    },
    regionFilterChipActive: {
      backgroundColor: theme.colors.button,
      borderColor: theme.colors.button,
    },
    regionFilterChipText: {
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      fontSize: 13,
    },
    regionFilterChipTextActive: {
      color: theme.colors.buttonText,
    },
    flag: {
      width: 62,
      height: 40,
      marginRight: 12,
      borderRadius: 4,
    },
    flagCountryDetails: {
      width: "100%",
      height: 150,
      marginBottom: 16,
      borderRadius: 8,
    },
    countryDetailsContent: {
      paddingBottom: 24,
    },
    countryBackRow: {
      alignSelf: "flex-start",
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingVertical: 8,
      paddingRight: 12,
      marginBottom: 8,
    },
    countryBackText: {
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      fontSize: 15,
    },
    countryHeroCard: {
      width: "100%",
      height: 170,
      borderRadius: 8,
      overflow: "hidden",
      backgroundColor: theme.colors.card,
      marginBottom: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.14,
      shadowRadius: 7,
      elevation: 4,
    },
    countryHeroFlag: {
      width: "100%",
      height: "100%",
    },
    countryHeroOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "rgba(0, 0, 0, 0.28)",
    },
    countryHeroText: {
      position: "absolute",
      left: 16,
      right: 16,
      bottom: 14,
    },
    countryHeroName: {
      color: "#FFFFFF",
      fontFamily: "Exo2-Bold",
      fontSize: 28,
      textShadowColor: "rgba(0, 0, 0, 0.45)",
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 4,
    },
    countryHeroRegion: {
      color: "#FFFFFF",
      fontFamily: "Exo2-Regular",
      fontSize: 15,
      marginTop: 4,
      opacity: 0.92,
    },
    countryTabRow: {
      flexDirection: "row",
      gap: 8,
      marginBottom: 14,
    },
    countryTab: {
      flex: 1,
      minHeight: 42,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    countryTabActive: {
      backgroundColor: theme.colors.button,
      borderColor: theme.colors.button,
    },
    countryTabText: {
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      fontSize: 13,
    },
    countryTabTextActive: {
      color: theme.colors.buttonText,
    },
    countryStatGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      marginBottom: 14,
    },
    countryStatCard: {
      width: "48%",
      minHeight: 88,
      padding: 12,
      borderRadius: 8,
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
      justifyContent: "space-between",
    },
    countryStatLabel: {
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      fontSize: 12,
      opacity: 0.72,
      textTransform: "uppercase",
    },
    countryStatValue: {
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      fontSize: 16,
      marginTop: 8,
    },
    countryFactCard: {
      padding: 14,
      borderRadius: 8,
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: 14,
    },
    countryFactHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginBottom: 8,
    },
    countryFactLabel: {
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      fontSize: 12,
      textTransform: "uppercase",
    },
    countryFactText: {
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      fontSize: 14,
      lineHeight: 20,
    },
    tabContent: {
      marginBottom: 14,
    },
    factItem: {
      padding: 14,
      borderRadius: 8,
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: 10,
    },
    factText: {
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      fontSize: 14,
      lineHeight: 20,
    },
    noFactsText: {
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      fontSize: 14,
      opacity: 0.72,
      textAlign: "center",
      paddingVertical: 24,
    },
    countryMiniMapCard: {
      height: 230,
      borderRadius: 8,
      overflow: "hidden",
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: 14,
    },
    countryMiniMap: {
      flex: 1,
    },
    countryCtaContent: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    // Enhanced CountryDetailsScreen styles for Material Design 3
    countryTopBar: {
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 8,
      marginBottom: 16,
    },
    countryTopBarButton: {
      padding: 8,
      borderRadius: 8,
      width: 40,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
    },
    countryTopBarSpacer: {
      flex: 1,
    },
    countryHeroSection: {
      marginBottom: 16,
    },
    countryHeaderCard: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: 14,
      borderRadius: 8,
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginTop: -8,
      marginHorizontal: 0,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.12,
      shadowRadius: 6,
      elevation: 3,
    },
    countryHeaderName: {
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      fontSize: 18,
      marginBottom: 4,
    },
    countryHeaderCapital: {
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      fontSize: 13,
      opacity: 0.74,
    },
    countryRegionBadge: {
      backgroundColor: theme.colors.button,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
    },
    countryRegionBadgeText: {
      color: theme.colors.buttonText,
      fontFamily: "Exo2-Bold",
      fontSize: 12,
    },
    countryStatGridContainer: {
      marginBottom: 14,
    },
    countryStatCardContent: {
      flex: 1,
    },
    countryInfoSection: {
      gap: 10,
      marginBottom: 14,
    },
    countryInfoCard: {
      padding: 14,
      borderRadius: 8,
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    countryInfoCardHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 8,
    },
    countryInfoCardIcon: {
      marginRight: 4,
    },
    countryInfoCardTitle: {
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      fontSize: 12,
      textTransform: "uppercase",
      opacity: 0.74,
    },
    countryInfoCardValue: {
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      fontSize: 16,
      marginTop: 4,
    },
    countryCtaSection: {
      gap: 10,
      marginTop: 8,
    },
    countryQuizButton: {
      backgroundColor: theme.colors.button,
    },
    countryMapButton: {
      backgroundColor: theme.colors.button,
      opacity: 0.85,
    },
    detailsCountryDetails: {
      padding: 16,
      width: "100%",
      backgroundColor: theme.colors.card,
      borderRadius: 8,
      marginBottom: 16,
    },
    buttonContainerCountryDetails: {
      marginTop: 16,
      alignItems: "center",
      backgroundColor: "#6200ee",
      padding: 12,
      borderRadius: 8,
    },
    cardContent: {
      flex: 1,
    },
    compareButton: {
      padding: 8,
      marginRight: 4,
      minWidth: 44,
      minHeight: 44,
      alignItems: "center",
      justifyContent: "center",
    },
    countryCard: {
      flexDirection: "row",
      alignItems: "center",
      padding: 12,
      borderRadius: 8,
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: 10,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
    },
    countryCardFlag: {
      width: 48,
      height: 32,
      borderRadius: 4,
      marginRight: 12,
      backgroundColor: "rgba(120, 120, 120, 0.18)",
    },
    countryCardMeta: {
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      fontSize: 13,
      marginTop: 3,
      opacity: 0.72,
    },
    skeletonRow: {
      flexDirection: "row",
      alignItems: "center",
      padding: 12,
      borderRadius: 8,
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: 10,
      opacity: 0.78,
    },
    skeletonFlag: {
      width: 48,
      height: 32,
      borderRadius: 4,
      marginRight: 12,
      backgroundColor: "rgba(140, 140, 140, 0.28)",
    },
    skeletonTextColumn: {
      flex: 1,
      gap: 8,
    },
    skeletonTitleLine: {
      width: "58%",
      height: 14,
      borderRadius: 4,
      backgroundColor: "rgba(140, 140, 140, 0.28)",
    },
    skeletonMetaLine: {
      width: "78%",
      height: 11,
      borderRadius: 4,
      backgroundColor: "rgba(140, 140, 140, 0.2)",
    },
    emptyStateText: {
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      fontSize: 15,
      textAlign: "center",
      marginTop: 24,
      opacity: 0.8,
    },
    dailyCountryCard: {
      width: "100%",
      padding: 14,
      borderRadius: 8,
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    dailyCountryHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 8,
    },
    dailyCountryEyebrow: {
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      fontSize: 13,
      opacity: 0.8,
    },
    dailyCountryContent: {
      flexDirection: "row",
      alignItems: "center",
    },
    dailyCountryFlag: {
      width: 72,
      height: 46,
      borderRadius: 4,
      marginRight: 12,
    },
    dailyCountryText: {
      flex: 1,
    },
    dailyCountryAction: {
      color: theme.colors.button,
      fontFamily: "Exo2-Bold",
      fontSize: 13,
    },
    dailyCountryActionRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      marginTop: 8,
    },
    dailyCountryLoader: {
      alignSelf: "flex-start",
      marginVertical: 8,
    },
    countryName: {
      fontSize: 18,
      fontFamily: "Exo2-Bold",
      color: theme.colors.text,
    },
    capitalText: {
      fontSize: 14,
      color: "#666666",
      fontFamily: "Exo2-Bold",
    },
    countryMetaText: {
      fontSize: 13,
      lineHeight: 18,
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      opacity: 0.72,
      marginTop: 3,
    },
    button: {
      backgroundColor: theme.colors.button,
      padding: 20,
      borderRadius: 8,
      alignItems: "center",
      marginBottom: 12,
    },
    correctOption: {
      backgroundColor: "#1B7F4C",
    },
    incorrectOption: {
      backgroundColor: "#B42318",
    },
    quizFeedbackCard: {
      padding: 16,
      borderRadius: 8,
      backgroundColor: theme.colors.card,
      marginBottom: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    quizFeedbackTitle: {
      fontSize: 20,
      color: theme.colors.text,
      fontFamily: "Exo2-Bold",
      marginBottom: 8,
    },
    quizFeedbackText: {
      fontSize: 16,
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      marginBottom: 8,
    },
    buttonText: {
      color: theme.colors.buttonText,
      fontFamily: "Exo2-Bold",
      fontSize: 15,
    },
    settingItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
      padding: 12,
      backgroundColor: theme.colors.card,
      borderRadius: 8,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    settingItemColumn: {
      marginBottom: 16,
      padding: 12,
      backgroundColor: theme.colors.card,
      borderRadius: 8,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    settingDescription: {
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      fontSize: 14,
      marginTop: 8,
    },
    settingMetaText: {
      color: theme.colors.text,
      fontFamily: "Exo2-Regular",
      fontSize: 13,
      marginTop: 10,
      opacity: 0.8,
    },
    settingError: {
      color: "#B42318",
      fontFamily: "Exo2-Bold",
      fontSize: 13,
      marginTop: 8,
    },
    settingLoader: {
      alignSelf: "flex-start",
      marginTop: 12,
    },
    settingActions: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginTop: 12,
    },
    settingActionButton: {
      backgroundColor: theme.colors.button,
      borderRadius: 8,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    settingActionButtonSecondary: {
      backgroundColor: "#3B82F6",
      borderRadius: 8,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    settingActionButtonDisabled: {
      opacity: 0.5,
    },
    settingActionText: {
      color: theme.colors.buttonText,
      fontFamily: "Exo2-Bold",
      fontSize: 14,
    },
    settingLinkText: {
      color: "#3B82F6",
      textDecorationLine: "underline",
    },
    picker: {
      width: 150,
      backgroundColor: theme.colors.card,
      borderRadius: 8,
      color: theme.colors.buttonText,
    },
    loaderContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      marginTop: 20,
    },
    exploreHeaderCard: {
      padding: 14,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.card,
      marginTop: 20,
      marginBottom: 14,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    exploreListContent: {
      paddingBottom: 96,
    },
    exploreEmptyState: {
      alignItems: "center",
      justifyContent: "center",
      padding: 24,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.card,
    },
  });
